import { create } from "zustand";

export type LauncherLanguage = "en" | "es" | "pt";

const STORAGE_KEY = "modstack.language";

const dictionaries = {
  en: {
    "nav.home": "Home",
    "nav.bedrock": "Bedrock",
    "nav.instances": "Instances",
    "nav.serverBrowser": "Server Browser",
    "nav.music": "Music",
    "nav.friends": "Friends",
    "nav.skins": "Skins",
    "nav.settings": "Settings",
    "frame.downloads": "Downloads",
    "frame.updateReady": "Update ready, click to reload",
    "settings.tabs.launcher": "Launcher",
    "settings.tabs.game": "Game",
    "settings.tabs.storage": "Storage",
    "settings.tabs.resources": "Resources",
    "settings.launcher.title": "Launcher",
    "settings.language.label": "Language More content coming soon!",
    "settings.language.description": "Choose the launcher language.",
    "settings.animations.label": "Enable animations",
    "settings.animations.description": "Smooth animations throughout the launcher.",
    "settings.animatedBackground.label": "Animated background",
    "settings.animatedBackground.description": "Play an animated background for the selected instance on the home screen.",
    "settings.hideLauncher.label": "Hide launcher",
    "settings.hideLauncher.description": "Hide the launcher when the game is running.",
    "settings.discordRpc.label": "Discord RPC",
    "settings.discordRpc.description": "Show your game status on Discord.",
    "settings.game.title": "Game",
    "settings.fullscreen.label": "Fullscreen",
    "settings.fullscreen.description": "Launch the game in fullscreen mode.",
    "settings.windowWidth": "Window width",
    "settings.windowHeight": "Window height",
    "settings.memoryAllocation": "Memory allocation",
    "settings.resources.title": "Resources",
    "settings.downloadConcurrency.label": "Download concurrency",
    "settings.downloadConcurrency.description": "Maximum number of files downloaded at the same time.",
    "settings.forceIpv4.label": "Force IPv4",
    "settings.forceIpv4.description": "Use IPv4 for downloads. Fixes connection issues on some networks.",
    "settings.storage.title": "Storage",
    "settings.installLocation": "Install location",
    "settings.installLocation.description": "Where Modstack stores game files, instances, and Bedrock data. Only affects new installations.",
    "settings.loading": "Loading...",
    "settings.custom": "custom",
    "settings.chooseFolder": "Choose folder",
    "settings.resetDefault": "Reset to default",
    "settings.migrationNote": "Existing installations won't be moved. To migrate, manually copy your files and reinstall.",
    "settings.installedInstances": "Installed Instances",
    "settings.noInstancesInstalled": "No instances installed.",
    "settings.uninstall": "Uninstall",
    "settings.cancel": "Cancel",
    "settings.confirm": "Confirm",
    "settings.uninstalling": "Uninstalling...",
    "settings.installed": "Installed",
    "settings.manualInstall": "Manual install",
    "home.selectInstance": "Select an instance",
    "home.search": "Search...",
    "home.noInstances": "No instances found",
    "home.downloading": "Downloading",
    "home.playing": "Playing",
    "home.starting": "Starting",
    "home.play": "Play",
    "home.addInstanceTitle": "Add Instance by Code",
    "home.addInstanceLabel": "Enter the code of the instance you want to add",
    "home.instanceCode": "Instance code",
    "home.addInstance": "Add Instance",
    "home.lockedInstance": "Locked instance",
    "home.lockedDescription": "requires a code to access. Enter the code you were given.",
    "home.accessCode": "Access code",
    "home.unlock": "Unlock",
    "home.signIn": "Sign in",
    "home.signInDescription": "You must be signed in to play.",
    "home.incorrectCode": "Incorrect code",
    "home.noInstanceWithCode": "No instance was found with that code.",
    "home.verifyCodeError": "Error verifying code",
    "home.tryAgain": "Please try again.",
    "home.unlocked": "unlocked successfully!",
    "music.previous": "Previous",
    "music.pause": "Pause",
    "music.play": "Play",
    "music.next": "Next",
    "music.close": "Close",
    "music.openMiniPlayer": "Open music player",
    "music.home": "Home",
    "music.library": "Library",
    "music.playlists": "Playlists",
    "music.queue": "Queue",
    "music.import": "Import",
    "music.searchPlaceholder": "Search music, artist, or playlist",
    "music.homeDescription": "Search YouTube tracks and import playlists into your library.",
    "music.saved": "saved",
    "music.results": "results",
    "music.resultsTitle": "Results",
    "music.recent": "Recent",
    "music.recommendations": "Recommendations",
    "music.emptyRecent": "Search for a song and add it to fill this section.",
    "music.noSavedMusic": "No saved music yet.",
    "music.playlistsDescription": "Create playlists from your queue or import one from YouTube or Spotify.",
    "music.playlistName": "Playlist name",
    "music.playlistPlaceholder": "Playlist",
    "music.backgroundImageUrl": "Background image URL",
    "music.createPlaylist": "Create playlist",
    "music.songs": "songs",
    "music.playAll": "Play all",
    "music.emptyPlaylist": "This playlist is empty.",
    "music.noPlaylists": "You have not created playlists yet.",
    "music.currentQueue": "Current queue",
    "music.localTitle": "Local title",
    "music.songName": "Song name",
    "music.artist": "Artist",
    "music.optional": "Optional",
    "music.directAudioUrl": "Direct audio URL",
    "music.addLocalAudio": "Add local audio",
    "music.importPlaylist": "Import playlist",
    "music.name": "Name",
    "music.newPlaylist": "New playlist",
    "music.importInto": "Import into",
    "music.youtubeLink": "YouTube link",
    "music.spotifyLink": "Spotify link",
    "music.add": "Add",
    "music.addToPlaylist": "Add to playlist",
    "music.added": "Added",
    "music.addedToPlaylist": "Added to playlist",
    "music.addedToQueue": "Added to queue",
    "music.noPreviewAvailable": "No preview available",
    "music.noPreviewDescription": "cannot be played from this provider.",
    "music.noResults": "No results",
    "music.tryAnotherTitle": "Try another title or artist.",
    "music.searchFailed": "Music search failed",
    "music.youtubeApiMissing": "Set VITE_YOUTUBE_API_KEY to enable YouTube.",
    "music.importedPlaylist": "Imported playlist",
    "music.playlistImported": "Playlist imported",
    "music.songsAdded": "songs added.",
    "music.importFailed": "Import failed",
    "music.importYoutubeFailed": "Check the link and VITE_YOUTUBE_API_KEY.",
    "music.importSpotifyFailed": "Check the link and Spotify environment variables.",
    "music.localSongAdded": "Local song added",
    "music.playlistSaved": "Playlist saved",
    "music.removedFromPlaylist": "Removed from playlist",
    "music.onlyNeededNewPlaylist": "Only needed when creating a new playlist",
    "music.myPlaylist": "My playlist",
    "music.mix.daily": "Daily Mix",
    "music.mix.dailySubtitle": "Personalized daily selection",
    "music.mix.topSongs": "Your top songs",
    "music.mix.topSongsSubtitle": "Recently repeated",
    "music.mix.trends": "Modstack Trends",
    "music.mix.trendsSubtitle": "Most played",
    "music.mix.discover": "Discover",
    "music.mix.discoverSubtitle": "Popular tracks you have not heard yet",
    "music.delete": "Deleted",
    "music.noDescription": "No description available",
    "music.edit": "Edit",
    "music.editPlaylist": "Edit playlist",
    "music.playlistNameLabel": "Name",
    "music.descriptionLabel": "Description",
    "music.noDescriptionPlaceholder": "No description",
    "music.cancel": "Cancel",
    "music.save": "Save",
    "music.changeLogo": "Change logo",
    "music.uploadLogo": "Upload logo",
    "music.removeLogo": "Remove logo",
    "music.importDescription": "Import a YouTube or Spotify playlist into your library",
    "music.importLink": "Link",
    "music.importSubmit": "Import playlist",
    "music.comingSoon": "coming soon",
    "music.playlistUpdated": "Playlist updated",
    "music.addToQueue": "Add to queue",
    "music.clearQueue": "Clear queue",
    "music.emptyQueue": "Queue is empty",
    "music.cannotRemove": "Cannot remove",
    "music.trackInPlaylist": "This track is in one or more playlists. Remove it from them first.",
    "music.removeTrack": "Remove from playlist",
    "app.loginSkin": "Log in to manage your skin",
    "friends.accountTitle": "Modstack Account",
    "friends.loginDescription": "Log in to use friends, chat and see what they are playing.",
    "friends.loginWaiting": "Finish logging in in your browser...",
    "friends.loggedIn": "Logged in",
    "friends.loginFailed": "Could not log in",
    "friends.connected": "Connected",
    "friends.connecting": "Connecting...",
    "friends.addByUsername": "Add by username",
    "friends.addFriend": "Add friend",
    "friends.incomingRequests": "Incoming requests",
    "friends.sent": "Sent",
    "friends.friends": "Friends",
    "friends.empty": "You have no friends added yet.",
    "friends.select": "Select a friend to start chatting",
    "friends.loadingMessages": "Loading messages...",
    "friends.noMessages": "No messages yet. Say hi",
    "friends.message": "Message",
    "friends.send": "Send",
    "friends.edit": "Edit",
    "friends.delete": "Delete",
    "friends.cancel": "Cancel",
    "friends.save": "Save",
    "friends.emoji": "Emoji",
    "friends.attachImage": "Attach image",
    "friends.imageUrl": "Image URL",
    "friends.playing": "Playing",
    "friends.online": "Online",
    "friends.offline": "Offline",
    "friends.requestSent": "Request sent to",
    "friends.sendFailed": "Could not send",
    "friends.logout": "Log out",
    "friends.accept": "Accept",
    "friends.decline": "Decline",
    "friends.removeFriend": "Remove friend",
    "friends.closeChat": "Close chat",
    "friends.noRequests": "No incoming requests.",
    "friends.directMessages": "Direct messages",
    "friends.edited": "edited",
    "logs.lines": "lines",
    "logs.title": "Logs",
    "logs.visible": "visible",
    "logs.all": "All",
    "logs.info": "Info",
    "logs.warn": "Warn",
    "logs.errors": "Errors",
    "logs.uploading": "Uploading...",
    "logs.upload": "mclo.gs",
    "logs.clear": "Clear",
    "logs.search": "Search logs...",
    "logs.autoScroll": "Auto-scroll",
    "logs.waiting": "Waiting for instance logs...",
    "logs.copied": "Log uploaded, URL copied to clipboard",
    "logs.uploadError": "Error uploading log",
    "capes.title": "Change cape",
    "capes.subtitle": "Wardrobe cape profile",
    "capes.dragToRotate": "Drag to rotate",
    "capes.loading": "Loading capes...",
    "capes.noCapes": "No capes found on your account.",
    "capes.none": "None",
    "capes.cancel": "Cancel",
    "capes.applying": "Applying...",
    "capes.select": "Select",
    "capes.applied": "Cape applied!",
    "capes.activated": "Cape activated ✓",
    "capes.removed": "Cape removed ✓",
    "capes.error": "Error",
    "capes.loadError": "Could not load capes.",
    "capes.applyError": "Could not apply cape.",
    "skins.title": "Wardrobe",
    "skins.beta": "BETA",
    "skins.nonPremium": "NON-PREMIUM",
    "skins.savedSkins": "Saved skins",
    "skins.applyingMicrosoft": "Applying on Microsoft...",
    "skins.dragToRotate": "Drag to rotate",
    "skins.changeCape": "Change cape",
    "skins.connectedMicrosoft": "✓ Connected to Microsoft — skins are applied automatically",
    "skins.nonPremiumTitle": "Non-premium mode",
    "skins.nonPremiumDesc": "Skin is applied in singleplayer and offline servers. Online servers with online-mode=true require a premium account.",
    "skins.addSkin": "Add skin",
    "skins.editSkin": "Edit skin",
    "skins.wardrobeProfile": "Wardrobe texture profile",
    "skins.name": "Name",
    "skins.namePlaceholder": "My skin...",
    "skins.texture": "Texture",
    "skins.replaceTexture": "Replace texture",
    "skins.armStyle": "Arm style",
    "skins.wide": "Wide",
    "skins.wideDesc": "Classic arms",
    "skins.slim": "Slim",
    "skins.slimDesc": "Thin arms",
    "skins.deleteSkin": "Delete skin",
    "skins.confirmDelete": "Are you sure?",
    "skins.delete": "Delete",
    "skins.cancel": "Cancel",
    "skins.saving": "Saving...",
    "skins.save": "Save",
    "skins.successTitle": "Success!",
    "skins.successDesc": "Skin applied on Microsoft ✓",
    "skins.uploadError": "Could not apply skin on Microsoft. Try signing out and back in.",
    "skins.noSkin": "No skin available",
    "skins.uploadToStart": "Upload a skin to get started",
    "running.running": "Running",
    "running.noInstances": "No instances running",
    "update.title": "Update downloaded",
    "update.desc": "Modstack App v{version} is ready to install. Reload to apply.",
    "update.reload": "Reload",
    "update.changelog": "Changelog",
    "user.signingIn": "Signing in...",
    "user.addOffline": "Add offline account",
    "user.pleaseWait": "Please wait...",
    "user.username": "Username",
    "user.usernamePlaceholder": "Between 3 and 16 characters",
    "user.cancel": "Cancel",
    "user.confirm": "Confirm",
    "user.buyMinecraft": "Buy Minecraft",
    "user.microsoft": "Microsoft",
    "user.offline": "Offline",
    "user.notLoggedIn": "Not logged in",
    "user.signInMicrosoft": "Sign in with Microsoft",
    "user.addMicrosoft": "Add Microsoft account",
    "user.playOffline": "Play offline",
    "user.signOut": "Sign out",
    "user.loginFailed": "Could not log in",
    "bedrock.checking": "Checking...",
    "bedrock.install": "Install Bedrock",
    "bedrock.installing": "Installing...",
    "bedrock.play": "Play Bedrock",
    "bedrock.launching": "Launching...",
    "bedrock.playing": "Playing",
    "bedrock.retry": "Retry",
    "bedrock.removeBackground": "Remove background",
    "bedrock.changeBackground": "Change background",
    "bedrock.alreadyInstalledStore": "Minecraft Bedrock is already installed from the Microsoft Store.",
    "bedrock.alreadyInstalled": "Minecraft Bedrock is already installed.",
    "bedrock.whatToDo": "What would you like to do?",
    "bedrock.launch": "Launch",
    "bedrock.reinstall": "Reinstall",
    "bedrock.dismiss": "Dismiss",
    "bedrock.errorStatus": "Error checking Bedrock status.",
    "sb.title": "Server browser",
    "sb.all": "All",
    "sb.allEditions": "All editions",
    "sb.java": "Java",
    "sb.bedrock": "Bedrock",
    "sb.crossplay": "Crossplay",
    "sb.mostVotes": "Most votes",
    "sb.mostPlayers": "Most players",
    "sb.recentlyAdded": "Recently added",
    "sb.random": "Random",
    "sb.mostFollowers": "Most followers",
    "sb.mostDownloads": "Most downloads",
    "sb.relevance": "Relevance",
    "sb.edition": "Edition",
    "sb.sort": "Sort",
    "sb.search": "Search",
    "sb.searchPlaceholder": "Search servers...",
    "sb.copyIp": "Copy IP",
    "sb.copied": "Copied",
    "sb.online": "Online",
    "sb.capacity": "Capacity",
    "sb.votes": "Votes",
    "sb.followers": "Followers",
    "sb.loadingCapes": "Loading capes...",
    "sb.noServers": "No servers found",
    "sb.couldNotLoad": "Could not load servers",
    "sb.tryAgain": "Try again",
    "sb.copyJoin": "Copy & join",
    "sb.readyToJoin": "Ready to join!",
    "sb.copyJoinDesc": "Server IP copied. Paste it in Minecraft.",
    "sb.ipCopied": "IP copied!",
    "sb.ipCopiedDesc": "copied to clipboard.",
    "sb.failedBoth": "Failed to fetch from both AnyServer.pro and Modrinth.",
    "sb.failedAnyserver": "Failed to fetch from AnyServer.pro. Only Modrinth shown.",
    "sb.failedModrinth": "Failed to fetch from Modrinth. Only AnyServer.pro shown.",
    "sb.errorLoading": "Error loading servers",
    "sb.voteOn": "Vote on AnyServer.pro",
    "sb.viewOn": "View on Modrinth",
    "sb.reviews": "Reviews",
    "sb.dragToRotate": "Drag to rotate",
    "inst.allInstances": "All instances",
    "inst.modpacks": "Modpacks",
    "inst.local": "Local",
    "inst.instancePrivate": "Instance Private",
    "inst.noInstances": "No instances found",
    "inst.createFirst": "Create your first instance",
    "inst.noLocalInstances": "No local instances",
    "inst.searchLocal": "Search local instances...",
    "inst.searchModpacks": "Search modpacks on Modrinth...",
    "inst.search": "Search",
    "inst.sortBy": "Sort by:",
    "inst.import": "Import",
    "inst.create": "Create instance",
    "inst.loading": "Loading...",
    "inst.createTitle": "Create instance",
    "inst.editTitle": "Edit instance",
    "inst.name": "Name",
    "inst.loader": "Loader",
    "inst.gameVersion": "Game version",
    "inst.suggestedModpack": "Suggested modpack",
    "inst.fetchingDetails": "Fetching details...",
    "inst.selectIcon": "Select icon",
    "inst.removeIcon": "Remove icon",
    "inst.selectBg": "Select bg",
    "inst.removeBg": "Remove bg",
    "inst.creating": "Creating...",
    "inst.saving": "Saving...",
    "inst.saveChanges": "Save changes",
    "inst.cancel": "Cancel",
    "inst.deleteInstance": "Delete instance",
    "inst.deleteWarning": "Deletes the entire folder. This cannot be undone.",
    "inst.confirmDelete": "Confirm delete",
    "inst.mainMenu": "Main menu",
    "inst.play": "Play",
    "inst.close": "Close",
    "inst.installing": "Installing",
    "inst.neverPlayed": "Never played",
    "inst.hoursPlayed": "{h}h {m}m played",
    "inst.minutesPlayed": "{m}m played",
    "inst.secondsPlayed": "{s}s played",
    "inst.browseContent": "Browse content",
    "inst.refreshMods": "Refresh",
    "inst.noContent": "No content installed",
    "inst.contentTab": "Content",
    "inst.filesTab": "Files",
    "inst.worldsTab": "Worlds",
    "inst.logsTab": "Logs",
    "inst.screenshotsTab": "Screenshots",
    "inst.installed": "Installed",
    "inst.install": "Install",
    "inst.installLatest": "Install latest",
    "inst.installContent": "Install content to instance",
    "inst.back": "Back",
    "inst.backToInstance": "Back to instance",
    "inst.description": "Description",
    "inst.versions": "Versions",
    "inst.gallery": "Gallery",
    "inst.noVersionsMatch": "No versions match filters",
    "inst.noGallery": "No gallery images",
    "inst.noResults": "No results found",
    "inst.searchError": "Search error",
    "inst.noModpacks": "No modpacks found",
    "inst.noWorlds": "No worlds found",
    "inst.noScreenshots": "No screenshots found",
    "inst.screenshotHint": "Press F2 in-game to take screenshots and they will appear here automatically.",
    "inst.screenshots": "screenshots",
    "inst.screenshot": "screenshot",
    "inst.refresh": "Refresh",
    "inst.openFolder": "Open folder",
    "inst.openInFolder": "Open in folder",
    "inst.copyFilename": "Copy filename",
    "inst.copyPath": "Copy full path",
    "inst.rename": "Rename",
    "inst.move": "Move",
    "inst.delete": "Delete",
    "inst.discard": "Discard",
    "inst.save": "Save",
    "inst.emptyFolder": "Empty folder",
    "inst.exportTitle": "Export modpack",
    "inst.exportName": "Modpack Name",
    "inst.exportVersion": "Version number",
    "inst.exportDescription": "Description",
    "inst.exportDescPlaceholder": "Enter modpack description...",
    "inst.exportFiles": "Configure which files are included in this export",
    "inst.exportSuccess": "Exported successfully!",
    "inst.exporting": "Exporting...",
    "inst.export": "Export",
    "inst.files": "Files",
    "inst.exportMenuItem": "Export",
    "inst.exportSaveAs": "Save as .mrstack",
    "inst.importedSuccess": "imported successfully!",
    "inst.importError": "Error importing",
    "inst.createdSuccess": "created",
    "inst.deletedToast": "Instance deleted",
    "inst.savedToast": "Changes saved",
    "inst.modRemoved": "removed",
    "inst.modUpdated": "updated",
    "inst.modInstalled": "installed successfully",
    "inst.errorInstalling": "Error installing",
    "inst.errorToggling": "Error toggling mod",
    "inst.errorUpdating": "Error updating mod",
    "inst.errorRemoving": "Error removing mod",
    "inst.errorSaving": "Error saving",
    "inst.errorDeleting": "Error deleting",
    "inst.errorRenaming": "Error renaming",
    "inst.errorOpenFolder": "Could not open folder",
    "inst.screenshotDeleted": "Screenshot deleted",
    "inst.errorDeletingScreenshot": "Error deleting screenshot",
    "inst.errorOpeningScreenshot": "Error opening screenshot",
    "inst.errorOpeningScreenshotsFolder": "Error opening screenshots folder",
    "inst.fileSaved": "File saved",
    "inst.errorSavingFile": "Error saving",
    "inst.lines": "lines",
    "inst.featured": "Featured",
    "inst.latest": "Latest",
    "inst.by": "by",
    "inst.updatedAgo": "Updated",
    "inst.noDescription": "No description",
    "inst.compatibility": "Compatibility",
    "inst.platforms": "Platforms",
    "inst.tags": "Tags",
    "inst.license": "License",
    "inst.lastUpdated": "Last updated",
    "inst.gameVersions": "Game versions",
    "inst.channels": "Channels",
    "inst.showAllVersions": "Show all versions",
    "inst.openOriginal": "Open original",
    "inst.openCurseForge": "CurseForge",
    "inst.noVersionsFound": "No versions found",
    "inst.all": "All",
    "inst.mods": "Mods",
    "inst.resourcePacks": "Resource Packs",
    "inst.dataPacks": "Data Packs",
    "inst.shaders": "Shaders",
    "inst.version": "Version",
    "inst.sortBy2": "Sort by",
    "inst.view": "View",
    "inst.modrinthSource": "Modrinth",
    "inst.curseforgeSource": "CurseForge",
  },
  es: {
    "nav.home": "Inicio",
    "nav.bedrock": "Bedrock",
    "nav.instances": "Instancias",
    "nav.serverBrowser": "Servidores",
    "nav.music": "Musica",
    "nav.friends": "Amigos",
    "nav.skins": "Skins",
    "nav.settings": "Ajustes",
    "frame.downloads": "Descargas",
    "frame.updateReady": "Actualizacion lista, haz clic para recargar",
    "settings.tabs.launcher": "Launcher",
    "settings.tabs.game": "Juego",
    "settings.tabs.storage": "Almacenamiento",
    "settings.tabs.resources": "Recursos",
    "settings.launcher.title": "Launcher",
    "settings.language.label": "Idioma Mas Proximamente!",
    "settings.language.description": "Elige el idioma del launcher.",
    "settings.animations.label": "Activar animaciones",
    "settings.animations.description": "Animaciones suaves en todo el launcher.",
    "settings.animatedBackground.label": "Fondo animado",
    "settings.animatedBackground.description": "Reproduce un fondo animado de la instancia seleccionada en inicio.",
    "settings.hideLauncher.label": "Ocultar launcher",
    "settings.hideLauncher.description": "Oculta el launcher cuando el juego esta ejecutandose.",
    "settings.discordRpc.label": "Discord RPC",
    "settings.discordRpc.description": "Muestra tu estado de juego en Discord.",
    "settings.game.title": "Juego",
    "settings.fullscreen.label": "Pantalla completa",
    "settings.fullscreen.description": "Inicia el juego en pantalla completa.",
    "settings.windowWidth": "Ancho de ventana",
    "settings.windowHeight": "Alto de ventana",
    "settings.memoryAllocation": "Memoria asignada",
    "settings.resources.title": "Recursos",
    "settings.downloadConcurrency.label": "Descargas simultáneas",
    "settings.downloadConcurrency.description": "Número máximo de archivos descargados al mismo tiempo.",
    "settings.forceIpv4.label": "Forzar IPv4",
    "settings.forceIpv4.description": "Usa IPv4 para las descargas. Soluciona problemas de conexión en algunas redes.",
    "settings.storage.title": "Almacenamiento",
    "settings.installLocation": "Ubicacion de instalacion",
    "settings.installLocation.description": "Donde Modstack guarda archivos del juego, instancias y datos de Bedrock. Solo afecta instalaciones nuevas.",
    "settings.loading": "Cargando...",
    "settings.custom": "personalizado",
    "settings.chooseFolder": "Elegir carpeta",
    "settings.resetDefault": "Restaurar",
    "settings.migrationNote": "Las instalaciones existentes no se moveran. Para migrar, copia tus archivos manualmente y reinstala.",
    "settings.installedInstances": "Instancias instaladas",
    "settings.noInstancesInstalled": "No hay instancias instaladas.",
    "settings.uninstall": "Desinstalar",
    "settings.cancel": "Cancelar",
    "settings.confirm": "Confirmar",
    "settings.uninstalling": "Desinstalando...",
    "settings.installed": "Instalado",
    "settings.manualInstall": "Instalacion manual",
    "home.selectInstance": "Selecciona una instancia",
    "home.search": "Buscar...",
    "home.noInstances": "No se encontraron instancias",
    "home.downloading": "Descargando",
    "home.playing": "Jugando",
    "home.starting": "Iniciando",
    "home.play": "Jugar",
    "home.addInstanceTitle": "Agregar instancia por codigo",
    "home.addInstanceLabel": "Ingresa el codigo de la instancia que quieres agregar",
    "home.instanceCode": "Codigo de instancia",
    "home.addInstance": "Agregar instancia",
    "home.lockedInstance": "Instancia bloqueada",
    "home.lockedDescription": "requiere un codigo para acceder. Ingresa el codigo que recibiste.",
    "home.accessCode": "Codigo de acceso",
    "home.unlock": "Desbloquear",
    "home.signIn": "Inicia sesion",
    "home.signInDescription": "Debes iniciar sesion para jugar.",
    "home.incorrectCode": "Codigo incorrecto",
    "home.noInstanceWithCode": "No se encontro una instancia con ese codigo.",
    "home.verifyCodeError": "Error verificando codigo",
    "home.tryAgain": "Intentalo de nuevo.",
    "home.unlocked": "desbloqueada correctamente!",
    "music.previous": "Anterior",
    "music.pause": "Pausar",
    "music.play": "Reproducir",
    "music.next": "Siguiente",
    "music.close": "Cerrar",
    "music.openMiniPlayer": "Abrir reproductor",
    "music.home": "Inicio",
    "music.library": "Biblioteca",
    "music.playlists": "Playlists",
    "music.queue": "Cola",
    "music.import": "Importar",
    "music.searchPlaceholder": "Buscar musica, artista o playlist",
    "music.homeDescription": "Busca canciones de YouTube e importa playlists a tu biblioteca.",
    "music.saved": "guardadas",
    "music.results": "resultados",
    "music.resultsTitle": "Resultados",
    "music.recent": "Reciente",
    "music.recommendations": "Recomendaciones",
    "music.emptyRecent": "Busca una cancion y agregala para llenar esta seccion.",
    "music.noSavedMusic": "Aun no hay musica guardada.",
    "music.playlistsDescription": "Crea playlists desde tu cola o importa una desde YouTube o Spotify.",
    "music.playlistName": "Nombre de playlist",
    "music.playlistPlaceholder": "Playlist",
    "music.backgroundImageUrl": "URL de imagen de fondo",
    "music.createPlaylist": "Crear playlist",
    "music.songs": "canciones",
    "music.playAll": "Reproducir todo",
    "music.emptyPlaylist": "Esta playlist esta vacia.",
    "music.noPlaylists": "Todavia no has creado playlists.",
    "music.currentQueue": "Cola actual",
    "music.localTitle": "Titulo local",
    "music.songName": "Nombre de la cancion",
    "music.artist": "Artista",
    "music.optional": "Opcional",
    "music.directAudioUrl": "URL directa de audio",
    "music.addLocalAudio": "Agregar audio local",
    "music.importPlaylist": "Importar playlist",
    "music.name": "Nombre",
    "music.newPlaylist": "Nueva playlist",
    "music.importInto": "Importar en",
    "music.youtubeLink": "Link de YouTube",
    "music.spotifyLink": "Link de Spotify",
    "music.add": "Agregar",
    "music.addToPlaylist": "Agregar a playlist",
    "music.added": "Agregada",
    "music.addedToPlaylist": "Agregada a playlist",
    "music.addedToQueue": "Agregada a la cola",
    "music.noPreviewAvailable": "Vista previa no disponible",
    "music.noPreviewDescription": "no se puede reproducir desde este proveedor.",
    "music.noResults": "Sin resultados",
    "music.tryAnotherTitle": "Prueba con otro titulo o artista.",
    "music.searchFailed": "La busqueda de musica fallo",
    "music.youtubeApiMissing": "Configura VITE_YOUTUBE_API_KEY para activar YouTube.",
    "music.importedPlaylist": "Playlist importada",
    "music.playlistImported": "Playlist importada",
    "music.songsAdded": "canciones agregadas.",
    "music.importFailed": "La importacion fallo",
    "music.importYoutubeFailed": "Revisa el link y VITE_YOUTUBE_API_KEY.",
    "music.importSpotifyFailed": "Revisa el link y las variables de Spotify.",
    "music.localSongAdded": "Cancion local agregada",
    "music.playlistSaved": "Playlist guardada",
    "music.removedFromPlaylist": "Eliminada de la playlist",
    "music.onlyNeededNewPlaylist": "Solo se necesita al crear una playlist nueva",
    "music.myPlaylist": "Mi playlist",
    "music.mix.daily": "Mix diario",
    "music.mix.dailySubtitle": "Seleccion diaria personalizada",
    "music.mix.topSongs": "Tus canciones top",
    "music.mix.topSongsSubtitle": "Repetidas recientemente",
    "music.mix.trends": "Tendencias Modstack",
    "music.mix.trendsSubtitle": "Mas reproducidas",
    "music.mix.discover": "Descubrir",
    "music.mix.discoverSubtitle": "Canciones populares que aun no escuchas",
    "music.delete": "Eliminada",
    "music.noDescription": "No hay descripcion disponible",
    "music.edit": "Editar",
    "music.editPlaylist": "Editar playlist",
    "music.playlistNameLabel": "Nombre",
    "music.descriptionLabel": "Descripción",
    "music.noDescriptionPlaceholder": "Sin descripción",
    "music.cancel": "Cancelar",
    "music.save": "Guardar",
    "music.changeLogo": "Cambiar logo",
    "music.uploadLogo": "Subir logo",
    "music.removeLogo": "Quitar logo",
    "music.importDescription": "Importa una playlist de YouTube o Spotify a tu biblioteca",
    "music.importLink": "Enlace",
    "music.importSubmit": "Importar playlist",
    "music.comingSoon": "próximamente",
    "music.playlistUpdated": "Playlist actualizada",
    "music.addToQueue": "Agregar a la cola",
    "music.clearQueue": "Limpiar cola",
    "music.emptyQueue": "La cola esta vacia",
    "music.cannotRemove": "No se puede eliminar",
    "music.trackInPlaylist": "Este track está en una o más playlists. Quítalo de ellas primero.",
    "music.removeTrack": "Eliminar de playlist",
    "app.loginSkin": "Inicia sesion para administrar tu skin",
    "friends.accountTitle": "Cuenta Modstack",
    "friends.loginDescription": "Inicia sesion para usar amigos, chat y ver que estan jugando.",
    "friends.loginWaiting": "Termina de iniciar sesion en tu navegador...",
    "friends.loggedIn": "Sesion iniciada",
    "friends.loginFailed": "No se pudo iniciar sesion",
    "friends.connected": "Conectado",
    "friends.connecting": "Conectando...",
    "friends.addByUsername": "Agregar por usuario",
    "friends.addFriend": "Agregar amigo",
    "friends.incomingRequests": "Solicitudes recibidas",
    "friends.sent": "Enviadas",
    "friends.friends": "Amigos",
    "friends.empty": "Aun no tienes amigos agregados.",
    "friends.select": "Selecciona un amigo para empezar a chatear",
    "friends.loadingMessages": "Cargando mensajes...",
    "friends.noMessages": "No hay mensajes todavia. Saluda",
    "friends.message": "Mensaje",
    "friends.send": "Enviar",
    "friends.edit": "Editar",
    "friends.delete": "Borrar",
    "friends.cancel": "Cancelar",
    "friends.save": "Guardar",
    "friends.emoji": "Emoji",
    "friends.attachImage": "Adjuntar imagen",
    "friends.imageUrl": "URL de imagen",
    "friends.playing": "Jugando",
    "friends.online": "En linea",
    "friends.offline": "Desconectado",
    "friends.requestSent": "Solicitud enviada a",
    "friends.sendFailed": "No se pudo enviar",
    "friends.logout": "Cerrar sesion",
    "friends.accept": "Aceptar",
    "friends.decline": "Rechazar",
    "friends.removeFriend": "Eliminar amigo",
    "friends.closeChat": "Cerrar chat",
    "friends.noRequests": "No hay solicitudes recibidas.",
    "friends.directMessages": "Mensajes directos",
    "friends.edited": "editado",
    "logs.lines": "lineas",
    "logs.title": "Logs",
    "logs.visible": "visibles",
    "logs.all": "Todo",
    "logs.info": "Info",
    "logs.warn": "Avisos",
    "logs.errors": "Errores",
    "logs.uploading": "Subiendo...",
    "logs.upload": "mclo.gs",
    "logs.clear": "Limpiar",
    "logs.search": "Buscar logs...",
    "logs.autoScroll": "Auto-scroll",
    "logs.waiting": "Esperando logs de la instancia...",
    "logs.copied": "Log subido, URL copiada al portapapeles",
    "logs.uploadError": "Error subiendo log",
    "capes.title": "Cambiar capa",
    "capes.subtitle": "Perfil de capa del guardarropa",
    "capes.dragToRotate": "Arrastra para rotar",
    "capes.loading": "Cargando capas...",
    "capes.noCapes": "No se encontraron capas en tu cuenta.",
    "capes.none": "Ninguna",
    "capes.cancel": "Cancelar",
    "capes.applying": "Aplicando...",
    "capes.select": "Seleccionar",
    "capes.applied": "¡Capa aplicada!",
    "capes.activated": "Capa activada ✓",
    "capes.removed": "Capa eliminada ✓",
    "capes.error": "Error",
    "capes.loadError": "No se pudieron cargar las capas.",
    "capes.applyError": "No se pudo aplicar la capa.",
    "skins.title": "Guardarropa",
    "skins.beta": "BETA",
    "skins.nonPremium": "NO PREMIUM",
    "skins.savedSkins": "Skins guardadas",
    "skins.applyingMicrosoft": "Aplicando en Microsoft...",
    "skins.dragToRotate": "Arrastra para rotar",
    "skins.changeCape": "Cambiar capa",
    "skins.connectedMicrosoft": "✓ Conectado a Microsoft — las skins se aplican automáticamente",
    "skins.nonPremiumTitle": "Modo no premium",
    "skins.nonPremiumDesc": "La skin se aplica en singleplayer y servidores offline. En servidores online con online-mode=true se requiere cuenta premium.",
    "skins.addSkin": "Agregar skin",
    "skins.editSkin": "Editar skin",
    "skins.wardrobeProfile": "Perfil de textura del guardarropa",
    "skins.name": "Nombre",
    "skins.namePlaceholder": "Mi skin...",
    "skins.texture": "Textura",
    "skins.replaceTexture": "Reemplazar textura",
    "skins.armStyle": "Estilo de brazos",
    "skins.wide": "Ancho",
    "skins.wideDesc": "Brazos clásicos",
    "skins.slim": "Delgado",
    "skins.slimDesc": "Brazos delgados",
    "skins.deleteSkin": "Eliminar skin",
    "skins.confirmDelete": "¿Estás seguro?",
    "skins.delete": "Eliminar",
    "skins.cancel": "Cancelar",
    "skins.saving": "Guardando...",
    "skins.save": "Guardar",
    "skins.successTitle": "¡Éxito!",
    "skins.successDesc": "Skin aplicada en Microsoft ✓",
    "skins.uploadError": "No se pudo aplicar la skin en Microsoft. Intenta cerrar sesión y volver a entrar.",
    "skins.noSkin": "Sin skin disponible",
    "skins.uploadToStart": "Sube una skin para comenzar",
    "running.running": "Ejecutando",
    "running.noInstances": "Sin instancias activas",
    "update.title": "Actualización descargada",
    "update.desc": "Modstack App v{version} lista para instalar. Recarga para aplicar.",
    "update.reload": "Recargar",
    "update.changelog": "Novedades",
    "user.signingIn": "Iniciando sesión...",
    "user.addOffline": "Agregar cuenta offline",
    "user.pleaseWait": "Por favor espera...",
    "user.username": "Usuario",
    "user.usernamePlaceholder": "Entre 3 y 16 caracteres",
    "user.cancel": "Cancelar",
    "user.confirm": "Confirmar",
    "user.buyMinecraft": "Comprar Minecraft",
    "user.microsoft": "Microsoft",
    "user.offline": "Offline",
    "user.notLoggedIn": "No has iniciado sesión",
    "user.signInMicrosoft": "Iniciar sesión con Microsoft",
    "user.addMicrosoft": "Agregar cuenta Microsoft",
    "user.playOffline": "Jugar offline",
    "user.signOut": "Cerrar sesión",
    "user.loginFailed": "No se pudo iniciar sesión",
    "bedrock.checking": "Verificando...",
    "bedrock.install": "Instalar Bedrock",
    "bedrock.installing": "Instalando...",
    "bedrock.play": "Jugar Bedrock",
    "bedrock.launching": "Iniciando...",
    "bedrock.playing": "Jugando",
    "bedrock.retry": "Reintentar",
    "bedrock.removeBackground": "Quitar fondo",
    "bedrock.changeBackground": "Cambiar fondo",
    "bedrock.alreadyInstalledStore": "Minecraft Bedrock ya está instalado desde Microsoft Store.",
    "bedrock.alreadyInstalled": "Minecraft Bedrock ya está instalado.",
    "bedrock.whatToDo": "¿Qué quieres hacer?",
    "bedrock.launch": "Lanzar",
    "bedrock.reinstall": "Reinstalar",
    "bedrock.dismiss": "Ignorar",
    "bedrock.errorStatus": "Error al verificar el estado de Bedrock.",
    "sb.title": "Explorador de servidores",
    "sb.all": "Todos",
    "sb.allEditions": "Todas las ediciones",
    "sb.java": "Java",
    "sb.bedrock": "Bedrock",
    "sb.crossplay": "Multiplataforma",
    "sb.mostVotes": "Más votos",
    "sb.mostPlayers": "Más jugadores",
    "sb.recentlyAdded": "Recién añadidos",
    "sb.random": "Aleatorio",
    "sb.mostFollowers": "Más seguidores",
    "sb.mostDownloads": "Más descargas",
    "sb.relevance": "Relevancia",
    "sb.edition": "Edición",
    "sb.sort": "Ordenar",
    "sb.search": "Buscar",
    "sb.searchPlaceholder": "Buscar servidores...",
    "sb.copyIp": "Copiar IP",
    "sb.copied": "Copiado",
    "sb.online": "En línea",
    "sb.capacity": "Capacidad",
    "sb.votes": "Votos",
    "sb.followers": "Seguidores",
    "sb.loadingCapes": "Cargando capas...",
    "sb.noServers": "No se encontraron servidores",
    "sb.couldNotLoad": "No se pudieron cargar los servidores",
    "sb.tryAgain": "Intentar de nuevo",
    "sb.copyJoin": "Copiar y unirse",
    "sb.readyToJoin": "¡Listo para unirse!",
    "sb.copyJoinDesc": "IP del servidor copiada. Pégala en Minecraft.",
    "sb.ipCopied": "¡IP copiada!",
    "sb.ipCopiedDesc": "copiada al portapapeles.",
    "sb.failedBoth": "Error al obtener de AnyServer.pro y Modrinth.",
    "sb.failedAnyserver": "Error al obtener de AnyServer.pro. Solo se muestra Modrinth.",
    "sb.failedModrinth": "Error al obtener de Modrinth. Solo se muestra AnyServer.pro.",
    "sb.errorLoading": "Error al cargar servidores",
    "sb.voteOn": "Votar en AnyServer.pro",
    "sb.viewOn": "Ver en Modrinth",
    "sb.reviews": "Reseñas",
    "sb.dragToRotate": "Arrastra para rotar",
    "inst.allInstances": "Todas las instancias",
    "inst.modpacks": "Modpacks",
    "inst.local": "Local",
    "inst.instancePrivate": "Instancia privada",
    "inst.noInstances": "No se encontraron instancias",
    "inst.createFirst": "Crea tu primera instancia",
    "inst.noLocalInstances": "No hay instancias locales",
    "inst.searchLocal": "Buscar instancias locales...",
    "inst.searchModpacks": "Buscar modpacks en Modrinth...",
    "inst.search": "Buscar",
    "inst.sortBy": "Ordenar por:",
    "inst.import": "Importar",
    "inst.create": "Crear instancia",
    "inst.loading": "Cargando...",
    "inst.createTitle": "Crear instancia",
    "inst.editTitle": "Editar instancia",
    "inst.name": "Nombre",
    "inst.loader": "Loader",
    "inst.gameVersion": "Version del juego",
    "inst.suggestedModpack": "Modpack sugerido",
    "inst.fetchingDetails": "Obteniendo detalles...",
    "inst.selectIcon": "Poner icono",
    "inst.removeIcon": "Quitar icono",
    "inst.selectBg": "Poner fondo",
    "inst.removeBg": "Quitar fondo",
    "inst.creating": "Creando...",
    "inst.saving": "Guardando...",
    "inst.saveChanges": "Guardar cambios",
    "inst.cancel": "Cancelar",
    "inst.deleteInstance": "Eliminar instancia",
    "inst.deleteWarning": "Elimina la carpeta completa. Esto no se puede deshacer.",
    "inst.confirmDelete": "Confirmar eliminacion",
    "inst.mainMenu": "Menu principal",
    "inst.play": "Jugar",
    "inst.close": "Cerrar",
    "inst.installing": "Instalando",
    "inst.neverPlayed": "Nunca jugado",
    "inst.hoursPlayed": "{h}h {m}m jugado",
    "inst.minutesPlayed": "{m}m jugado",
    "inst.secondsPlayed": "{s}s jugado",
    "inst.browseContent": "Explorar contenido",
    "inst.refreshMods": "Actualizar",
    "inst.noContent": "Sin contenido instalado",
    "inst.contentTab": "Contenido",
    "inst.filesTab": "Archivos",
    "inst.worldsTab": "Mundos",
    "inst.logsTab": "Logs",
    "inst.screenshotsTab": "Capturas",
    "inst.installed": "Instalado",
    "inst.install": "Instalar",
    "inst.installLatest": "Instalar ultima version",
    "inst.installContent": "Instalar contenido en la instancia",
    "inst.back": "Atras",
    "inst.backToInstance": "Volver a la instancia",
    "inst.description": "Descripcion",
    "inst.versions": "Versiones",
    "inst.gallery": "Galeria",
    "inst.noVersionsMatch": "Ninguna version coincide con los filtros",
    "inst.noGallery": "Sin imagenes en la galeria",
    "inst.noResults": "Sin resultados",
    "inst.searchError": "Error de busqueda",
    "inst.noModpacks": "No se encontraron modpacks",
    "inst.noWorlds": "No se encontraron mundos",
    "inst.noScreenshots": "No se encontraron capturas",
    "inst.screenshotHint": "Presiona F2 en el juego para tomar capturas y apareceran aqui automaticamente.",
    "inst.screenshots": "capturas",
    "inst.screenshot": "captura",
    "inst.refresh": "Actualizar",
    "inst.openFolder": "Abrir carpeta",
    "inst.openInFolder": "Abrir en carpeta",
    "inst.copyFilename": "Copiar nombre",
    "inst.copyPath": "Copiar ruta completa",
    "inst.rename": "Renombrar",
    "inst.move": "Mover",
    "inst.delete": "Eliminar",
    "inst.discard": "Descartar",
    "inst.save": "Guardar",
    "inst.emptyFolder": "Carpeta vacia",
    "inst.exportTitle": "Exportar modpack",
    "inst.exportName": "Nombre del modpack",
    "inst.exportVersion": "Numero de version",
    "inst.exportDescription": "Descripcion",
    "inst.exportDescPlaceholder": "Ingresa la descripcion del modpack...",
    "inst.exportFiles": "Configura que archivos se incluyen en esta exportacion",
    "inst.exportSuccess": "Exportado correctamente!",
    "inst.exporting": "Exportando...",
    "inst.export": "Exportar",
    "inst.files": "Archivos",
    "inst.exportMenuItem": "Exportar",
    "inst.exportSaveAs": "Guardar como .mrstack",
    "inst.importedSuccess": "importada correctamente!",
    "inst.importError": "Error al importar",
    "inst.createdSuccess": "creada",
    "inst.deletedToast": "Instancia eliminada",
    "inst.savedToast": "Cambios guardados",
    "inst.modRemoved": "eliminado",
    "inst.modUpdated": "actualizado",
    "inst.modInstalled": "instalado correctamente",
    "inst.errorInstalling": "Error al instalar",
    "inst.errorToggling": "Error al activar/desactivar mod",
    "inst.errorUpdating": "Error al actualizar mod",
    "inst.errorRemoving": "Error al eliminar mod",
    "inst.errorSaving": "Error al guardar",
    "inst.errorDeleting": "Error al eliminar",
    "inst.errorRenaming": "Error al renombrar",
    "inst.errorOpenFolder": "No se pudo abrir la carpeta",
    "inst.screenshotDeleted": "Captura eliminada",
    "inst.errorDeletingScreenshot": "Error al eliminar captura",
    "inst.errorOpeningScreenshot": "Error al abrir captura",
    "inst.errorOpeningScreenshotsFolder": "Error al abrir la carpeta de capturas",
    "inst.fileSaved": "Archivo guardado",
    "inst.errorSavingFile": "Error al guardar",
    "inst.lines": "lineas",
    "inst.featured": "Destacado",
    "inst.latest": "Ultima",
    "inst.by": "por",
    "inst.updatedAgo": "Actualizado",
    "inst.noDescription": "Sin descripcion",
    "inst.compatibility": "Compatibilidad",
    "inst.platforms": "Plataformas",
    "inst.tags": "Etiquetas",
    "inst.license": "Licencia",
    "inst.lastUpdated": "Ultima actualizacion",
    "inst.gameVersions": "Versiones del juego",
    "inst.channels": "Canales",
    "inst.showAllVersions": "Mostrar todas las versiones",
    "inst.openOriginal": "Abrir original",
    "inst.openCurseForge": "CurseForge",
    "inst.noVersionsFound": "No se encontraron versiones",
    "inst.all": "Todos",
    "inst.mods": "Mods",
    "inst.resourcePacks": "Paquetes de recursos",
    "inst.dataPacks": "Paquetes de datos",
    "inst.shaders": "Shaders",
    "inst.version": "Version",
    "inst.sortBy2": "Ordenar por",
    "inst.view": "Ver",
    "inst.modrinthSource": "Modrinth",
    "inst.curseforgeSource": "CurseForge",
  },
  pt: {
    "nav.home": "Inicio",
    "nav.bedrock": "Bedrock",
    "nav.instances": "Instancias",
    "nav.serverBrowser": "Servidores",
    "nav.music": "Musica",
    "nav.friends": "Amigos",
    "nav.skins": "Skins",
    "nav.settings": "Configuracoes",
    "frame.downloads": "Downloads",
    "frame.updateReady": "Atualizacao pronta, clique para recarregar",
    "settings.tabs.launcher": "Launcher",
    "settings.tabs.game": "Jogo",
    "settings.tabs.storage": "Armazenamento",
    "settings.tabs.resources": "Recursos",
    "settings.launcher.title": "Launcher",
    "settings.language.label": "Mais conteúdo em breve!",
    "settings.language.description": "Escolha o idioma do launcher.",
    "settings.animations.label": "Ativar animacoes",
    "settings.animations.description": "Animacoes suaves em todo o launcher.",
    "settings.animatedBackground.label": "Fundo animado",
    "settings.animatedBackground.description": "Reproduz um fundo animado da instancia selecionada na tela inicial.",
    "settings.hideLauncher.label": "Ocultar launcher",
    "settings.hideLauncher.description": "Oculta o launcher enquanto o jogo esta rodando.",
    "settings.discordRpc.label": "Discord RPC",
    "settings.discordRpc.description": "Mostra seu status de jogo no Discord.",
    "settings.game.title": "Jogo",
    "settings.fullscreen.label": "Tela cheia",
    "settings.fullscreen.description": "Inicia o jogo em tela cheia.",
    "settings.windowWidth": "Largura da janela",
    "settings.windowHeight": "Altura da janela",
    "settings.memoryAllocation": "Memoria alocada",
    "settings.resources.title": "Recursos",
    "settings.downloadConcurrency.label": "Downloads simultâneos",
    "settings.downloadConcurrency.description": "Número máximo de arquivos baixados ao mesmo tempo.",
    "settings.forceIpv4.label": "Forçar IPv4",
    "settings.forceIpv4.description": "Usa IPv4 para os downloads. Corrige problemas de conexão em algumas redes.",
    "settings.storage.title": "Armazenamento",
    "settings.installLocation": "Local de instalacao",
    "settings.installLocation.description": "Onde o Modstack guarda arquivos do jogo, instancias e dados do Bedrock. Afeta apenas novas instalacoes.",
    "settings.loading": "Carregando...",
    "settings.custom": "personalizado",
    "settings.chooseFolder": "Escolher pasta",
    "settings.resetDefault": "Restaurar",
    "settings.migrationNote": "Instalacoes existentes nao serao movidas. Para migrar, copie os arquivos manualmente e reinstale.",
    "settings.installedInstances": "Instancias instaladas",
    "settings.noInstancesInstalled": "Nenhuma instancia instalada.",
    "settings.uninstall": "Desinstalar",
    "settings.cancel": "Cancelar",
    "settings.confirm": "Confirmar",
    "settings.uninstalling": "Desinstalando...",
    "settings.installed": "Instalado",
    "settings.manualInstall": "Instalacao manual",
    "home.selectInstance": "Selecione uma instancia",
    "home.search": "Buscar...",
    "home.noInstances": "Nenhuma instancia encontrada",
    "home.downloading": "Baixando",
    "home.playing": "Jogando",
    "home.starting": "Iniciando",
    "home.play": "Jogar",
    "home.addInstanceTitle": "Adicionar instancia por codigo",
    "home.addInstanceLabel": "Digite o codigo da instancia que deseja adicionar",
    "home.instanceCode": "Codigo da instancia",
    "home.addInstance": "Adicionar instancia",
    "home.lockedInstance": "Instancia bloqueada",
    "home.lockedDescription": "precisa de um codigo para acessar. Digite o codigo recebido.",
    "home.accessCode": "Codigo de acesso",
    "home.unlock": "Desbloquear",
    "home.signIn": "Entrar",
    "home.signInDescription": "Voce precisa entrar para jogar.",
    "home.incorrectCode": "Codigo incorreto",
    "home.noInstanceWithCode": "Nenhuma instancia foi encontrada com esse codigo.",
    "home.verifyCodeError": "Erro ao verificar codigo",
    "home.tryAgain": "Tente novamente.",
    "home.unlocked": "desbloqueada com sucesso!",
    "music.previous": "Anterior",
    "music.pause": "Pausar",
    "music.play": "Reproduzir",
    "music.next": "Proxima",
    "music.close": "Fechar",
    "music.openMiniPlayer": "Abrir reprodutor",
    "music.home": "Inicio",
    "music.library": "Biblioteca",
    "music.playlists": "Playlists",
    "music.queue": "Fila",
    "music.import": "Importar",
    "music.searchPlaceholder": "Buscar musica, artista ou playlist",
    "music.homeDescription": "Busque faixas do YouTube e importe playlists para sua biblioteca.",
    "music.saved": "salvas",
    "music.results": "resultados",
    "music.resultsTitle": "Resultados",
    "music.recent": "Recentes",
    "music.recommendations": "Recomendacoes",
    "music.emptyRecent": "Busque uma musica e adicione para preencher esta secao.",
    "music.noSavedMusic": "Ainda nao ha musicas salvas.",
    "music.playlistsDescription": "Crie playlists da sua fila ou importe uma do YouTube ou Spotify.",
    "music.playlistName": "Nome da playlist",
    "music.playlistPlaceholder": "Playlist",
    "music.backgroundImageUrl": "URL da imagem de fundo",
    "music.createPlaylist": "Criar playlist",
    "music.songs": "musicas",
    "music.playAll": "Reproduzir tudo",
    "music.emptyPlaylist": "Esta playlist esta vazia.",
    "music.noPlaylists": "Voce ainda nao criou playlists.",
    "music.currentQueue": "Fila atual",
    "music.localTitle": "Titulo local",
    "music.songName": "Nome da musica",
    "music.artist": "Artista",
    "music.optional": "Opcional",
    "music.directAudioUrl": "URL direta do audio",
    "music.addLocalAudio": "Adicionar audio local",
    "music.importPlaylist": "Importar playlist",
    "music.name": "Nome",
    "music.newPlaylist": "Nova playlist",
    "music.importInto": "Importar para",
    "music.youtubeLink": "Link do YouTube",
    "music.spotifyLink": "Link do Spotify",
    "music.add": "Adicionar",
    "music.addToPlaylist": "Adicionar a playlist",
    "music.added": "Adicionada",
    "music.addedToPlaylist": "Adicionada a playlist",
    "music.addedToQueue": "Adicionada a fila",
    "music.noPreviewAvailable": "Previa indisponivel",
    "music.noPreviewDescription": "nao pode ser reproduzida por este provedor.",
    "music.noResults": "Sem resultados",
    "music.tryAnotherTitle": "Tente outro titulo ou artista.",
    "music.searchFailed": "A busca de musica falhou",
    "music.youtubeApiMissing": "Configure VITE_YOUTUBE_API_KEY para ativar YouTube.",
    "music.importedPlaylist": "Playlist importada",
    "music.playlistImported": "Playlist importada",
    "music.songsAdded": "musicas adicionadas.",
    "music.importFailed": "A importacao falhou",
    "music.importYoutubeFailed": "Verifique o link e VITE_YOUTUBE_API_KEY.",
    "music.importSpotifyFailed": "Verifique o link e as variaveis do Spotify.",
    "music.localSongAdded": "Musica local adicionada",
    "music.playlistSaved": "Playlist salva",
    "music.removedFromPlaylist": "Removida da playlist",
    "music.onlyNeededNewPlaylist": "Necessario apenas ao criar uma nova playlist",
    "music.myPlaylist": "Minha playlist",
    "music.mix.daily": "Mix diario",
    "music.mix.dailySubtitle": "Selecao diaria personalizada",
    "music.mix.topSongs": "Suas musicas top",
    "music.mix.topSongsSubtitle": "Repetidas recentemente",
    "music.mix.trends": "Tendencias Modstack",
    "music.mix.trendsSubtitle": "Mais reproduzidas",
    "music.mix.discover": "Descobrir",
    "music.mix.discoverSubtitle": "Musicas populares que voce ainda nao ouviu",
    "music.delete": "Deletada",
    "music.noDescription": "Nenhuma descricao disponivel",
    "music.edit": "Editar",
    "music.editPlaylist": "Editar playlist",
    "music.playlistNameLabel": "Nome",
    "music.descriptionLabel": "Descrição",
    "music.noDescriptionPlaceholder": "Sem descrição",
    "music.cancel": "Cancelar",
    "music.save": "Salvar",
    "music.changeLogo": "Trocar logo",
    "music.uploadLogo": "Enviar logo",
    "music.removeLogo": "Remover logo",
    "music.importDescription": "Importe uma playlist do YouTube ou Spotify para sua biblioteca",
    "music.importLink": "Link",
    "music.importSubmit": "Importar playlist",
    "music.comingSoon": "em breve",
    "music.playlistUpdated": "Playlist atualizada",
    "music.clearQueue": "Limpar fila",
    "music.addToQueue": "Adicionar a fila",
    "music.emptyQueue": "A fila esta vazia. Adicione musicas para começar a tocar.",
    "music.cannotRemove": "Não é possível remover",
    "music.removeTrack": "Remover da playlist",
    "music.trackInPlaylist": "Esta faixa esta em uma ou mais playlists. Remova-a delas primeiro.",
    "app.loginSkin": "Entre para gerenciar sua skin",
    "friends.accountTitle": "Conta Modstack",
    "friends.loginDescription": "Entre para usar amigos, chat e ver o que estao jogando.",
    "friends.loginWaiting": "Termine o login no navegador...",
    "friends.loggedIn": "Login feito",
    "friends.loginFailed": "Nao foi possivel entrar",
    "friends.connected": "Conectado",
    "friends.connecting": "Conectando...",
    "friends.addByUsername": "Adicionar por usuario",
    "friends.addFriend": "Adicionar amigo",
    "friends.incomingRequests": "Solicitacoes recebidas",
    "friends.sent": "Enviadas",
    "friends.friends": "Amigos",
    "friends.empty": "Voce ainda nao adicionou amigos.",
    "friends.select": "Selecione um amigo para conversar",
    "friends.loadingMessages": "Carregando mensagens...",
    "friends.noMessages": "Ainda nao ha mensagens. Diga oi",
    "friends.message": "Mensagem",
    "friends.send": "Enviar",
    "friends.edit": "Editar",
    "friends.delete": "Excluir",
    "friends.cancel": "Cancelar",
    "friends.save": "Salvar",
    "friends.emoji": "Emoji",
    "friends.attachImage": "Anexar imagem",
    "friends.imageUrl": "URL da imagem",
    "friends.playing": "Jogando",
    "friends.online": "Online",
    "friends.offline": "Offline",
    "friends.requestSent": "Solicitacao enviada para",
    "friends.sendFailed": "Nao foi possivel enviar",
    "friends.logout": "Sair",
    "friends.accept": "Aceitar",
    "friends.decline": "Recusar",
    "friends.removeFriend": "Remover amigo",
    "friends.closeChat": "Fechar chat",
    "friends.noRequests": "Nao ha solicitacoes recebidas.",
    "friends.directMessages": "Mensagens diretas", 
    "friends.edited": "editado",
    "logs.lines": "linhas",
    "logs.title": "Logs",
    "logs.visible": "visiveis",
    "logs.all": "Tudo",
    "logs.info": "Info",
    "logs.warn": "Avisos",
    "logs.errors": "Erros",
    "logs.uploading": "Enviando...",
    "logs.upload": "mclo.gs",
    "logs.clear": "Limpar",
    "logs.search": "Buscar logs...",
    "logs.autoScroll": "Auto-scroll",
    "logs.waiting": "Aguardando logs da instancia...",
    "logs.copied": "Log enviado, URL copiada para a area de transferencia",
    "logs.uploadError": "Erro ao enviar log",
    "capes.title": "Trocar capa",
    "capes.subtitle": "Perfil de capa do guarda-roupa",
    "capes.dragToRotate": "Arraste para girar",
    "capes.loading": "Carregando capas...",
    "capes.noCapes": "Nenhuma capa encontrada na sua conta.",
    "capes.none": "Nenhuma",
    "capes.cancel": "Cancelar",
    "capes.applying": "Aplicando...",
    "capes.select": "Selecionar",
    "capes.applied": "Capa aplicada!",
    "capes.activated": "Capa ativada ✓",
    "capes.removed": "Capa removida ✓",
    "capes.error": "Erro",
    "capes.loadError": "Não foi possível carregar as capas.",
    "capes.applyError": "Não foi possível aplicar a capa.",
    "skins.title": "Guarda-roupa",
    "skins.beta": "BETA",
    "skins.nonPremium": "NÃO PREMIUM",
    "skins.savedSkins": "Skins salvas",
    "skins.applyingMicrosoft": "Aplicando no Microsoft...",
    "skins.dragToRotate": "Arraste para girar",
    "skins.changeCape": "Trocar capa",
    "skins.connectedMicrosoft": "✓ Conectado ao Microsoft — skins são aplicadas automaticamente",
    "skins.nonPremiumTitle": "Modo não premium",
    "skins.nonPremiumDesc": "A skin é aplicada no singleplayer e servidores offline. Servidores online com online-mode=true exigem conta premium.",
    "skins.addSkin": "Adicionar skin",
    "skins.editSkin": "Editar skin",
    "skins.wardrobeProfile": "Perfil de textura do guarda-roupa",
    "skins.name": "Nome",
    "skins.namePlaceholder": "Minha skin...",
    "skins.texture": "Textura",
    "skins.replaceTexture": "Substituir textura",
    "skins.armStyle": "Estilo de braços",
    "skins.wide": "Largo",
    "skins.wideDesc": "Braços clássicos",
    "skins.slim": "Fino",
    "skins.slimDesc": "Braços finos",
    "skins.deleteSkin": "Excluir skin",
    "skins.confirmDelete": "Tem certeza?",
    "skins.delete": "Excluir",
    "skins.cancel": "Cancelar",
    "skins.saving": "Salvando...",
    "skins.save": "Salvar",
    "skins.successTitle": "Sucesso!",
    "skins.successDesc": "Skin aplicada no Microsoft ✓",
    "skins.uploadError": "Não foi possível aplicar a skin no Microsoft. Tente sair e entrar novamente.",
    "skins.noSkin": "Nenhuma skin disponível",
    "skins.uploadToStart": "Envie uma skin para começar",
    "running.running": "Executando",
    "running.noInstances": "Nenhuma instância ativa",
    "update.title": "Atualização baixada",
    "update.desc": "Modstack App v{version} pronta para instalar. Recarregue para aplicar.",
    "update.reload": "Recarregar",
    "update.changelog": "Novidades",
    "user.signingIn": "Entrando...",
    "user.addOffline": "Adicionar conta offline",
    "user.pleaseWait": "Por favor aguarde...",
    "user.username": "Usuário",
    "user.usernamePlaceholder": "Entre 3 e 16 caracteres",
    "user.cancel": "Cancelar",
    "user.confirm": "Confirmar",
    "user.buyMinecraft": "Comprar Minecraft",
    "user.microsoft": "Microsoft",
    "user.offline": "Offline",
    "user.notLoggedIn": "Não conectado",
    "user.signInMicrosoft": "Entrar com Microsoft",
    "user.addMicrosoft": "Adicionar conta Microsoft",
    "user.playOffline": "Jogar offline",
    "user.signOut": "Sair",
    "user.loginFailed": "Não foi possível entrar",
    "bedrock.checking": "Verificando...",
    "bedrock.install": "Instalar Bedrock",
    "bedrock.installing": "Instalando...",
    "bedrock.play": "Jogar Bedrock",
    "bedrock.launching": "Iniciando...",
    "bedrock.playing": "Jogando",
    "bedrock.retry": "Tentar novamente",
    "bedrock.removeBackground": "Remover fundo",
    "bedrock.changeBackground": "Trocar fundo",
    "bedrock.alreadyInstalledStore": "Minecraft Bedrock já está instalado pela Microsoft Store.",
    "bedrock.alreadyInstalled": "Minecraft Bedrock já está instalado.",
    "bedrock.whatToDo": "O que você gostaria de fazer?",
    "bedrock.launch": "Iniciar",
    "bedrock.reinstall": "Reinstalar",
    "bedrock.dismiss": "Ignorar",
    "bedrock.errorStatus": "Erro ao verificar o status do Bedrock.",
    "sb.title": "Explorador de servidores",
    "sb.all": "Todos",
    "sb.allEditions": "Todas as edições",
    "sb.java": "Java",
    "sb.bedrock": "Bedrock",
    "sb.crossplay": "Multiplataforma",
    "sb.mostVotes": "Mais votos",
    "sb.mostPlayers": "Mais jogadores",
    "sb.recentlyAdded": "Adicionados recentemente",
    "sb.random": "Aleatório",
    "sb.mostFollowers": "Mais seguidores",
    "sb.mostDownloads": "Mais downloads",
    "sb.relevance": "Relevância",
    "sb.edition": "Edição",
    "sb.sort": "Ordenar",
    "sb.search": "Buscar",
    "sb.searchPlaceholder": "Buscar servidores...",
    "sb.copyIp": "Copiar IP",
    "sb.copied": "Copiado",
    "sb.online": "Online",
    "sb.capacity": "Capacidade",
    "sb.votes": "Votos",
    "sb.followers": "Seguidores",
    "sb.loadingCapes": "Carregando capas...",
    "sb.noServers": "Nenhum servidor encontrado",
    "sb.couldNotLoad": "Não foi possível carregar servidores",
    "sb.tryAgain": "Tentar novamente",
    "sb.copyJoin": "Copiar e entrar",
    "sb.readyToJoin": "Pronto para entrar!",
    "sb.copyJoinDesc": "IP do servidor copiado. Cole no Minecraft.",
    "sb.ipCopied": "IP copiado!",
    "sb.ipCopiedDesc": "copiado para a área de transferência.",
    "sb.failedBoth": "Falha ao buscar de AnyServer.pro e Modrinth.",
    "sb.failedAnyserver": "Falha ao buscar de AnyServer.pro. Apenas Modrinth exibido.",
    "sb.failedModrinth": "Falha ao buscar de Modrinth. Apenas AnyServer.pro exibido.",
    "sb.errorLoading": "Erro ao carregar servidores",
    "sb.voteOn": "Votar no AnyServer.pro",
    "sb.viewOn": "Ver no Modrinth",
    "sb.reviews": "Avaliações",
    "sb.dragToRotate": "Arraste para girar",
    "inst.allInstances": "Todas as instancias",
    "inst.modpacks": "Modpacks",
    "inst.local": "Local",
    "inst.instancePrivate": "Instancia privada",
    "inst.noInstances": "Nenhuma instancia encontrada",
    "inst.createFirst": "Crie sua primeira instancia",
    "inst.noLocalInstances": "Nenhuma instancia local",
    "inst.searchLocal": "Buscar instancias locais...",
    "inst.searchModpacks": "Buscar modpacks no Modrinth...",
    "inst.search": "Buscar",
    "inst.sortBy": "Ordenar por:",
    "inst.import": "Importar",
    "inst.create": "Criar instancia",
    "inst.loading": "Carregando...",
    "inst.createTitle": "Criar instancia",
    "inst.editTitle": "Editar instancia",
    "inst.name": "Nome",
    "inst.loader": "Loader",
    "inst.gameVersion": "Versao do jogo",
    "inst.suggestedModpack": "Modpack sugerido",
    "inst.fetchingDetails": "Buscando detalhes...",
    "inst.selectIcon": "Subir icone",
    "inst.removeIcon": "Remover icone",
    "inst.selectBg": "Subir fundo",
    "inst.removeBg": "Remover fundo",
    "inst.creating": "Criando...",
    "inst.saving": "Salvando...",
    "inst.saveChanges": "Salvar alteracoes",
    "inst.cancel": "Cancelar",
    "inst.deleteInstance": "Excluir instancia",
    "inst.deleteWarning": "Exclui a pasta inteira. Isso nao pode ser desfeito.",
    "inst.confirmDelete": "Confirmar exclusao",
    "inst.mainMenu": "Menu principal",
    "inst.play": "Jogar",
    "inst.close": "Fechar",
    "inst.installing": "Instalando",
    "inst.neverPlayed": "Nunca jogado",
    "inst.hoursPlayed": "{h}h {m}m jogado",
    "inst.minutesPlayed": "{m}m jogado",
    "inst.secondsPlayed": "{s}s jogado",
    "inst.browseContent": "Explorar conteudo",
    "inst.refreshMods": "Atualizar",
    "inst.noContent": "Sem conteudo instalado",
    "inst.contentTab": "Conteudo",
    "inst.filesTab": "Arquivos",
    "inst.worldsTab": "Mundos",
    "inst.logsTab": "Logs",
    "inst.screenshotsTab": "Capturas",
    "inst.installed": "Instalado",
    "inst.install": "Instalar",
    "inst.installLatest": "Instalar ultima versao",
    "inst.installContent": "Instalar conteudo na instancia",
    "inst.back": "Voltar",
    "inst.backToInstance": "Voltar a instancia",
    "inst.description": "Descricao",
    "inst.versions": "Versoes",
    "inst.gallery": "Galeria",
    "inst.noVersionsMatch": "Nenhuma versao coincide com os filtros",
    "inst.noGallery": "Sem imagens na galeria",
    "inst.noResults": "Sem resultados",
    "inst.searchError": "Erro de busca",
    "inst.noModpacks": "Nenhum modpack encontrado",
    "inst.noWorlds": "Nenhum mundo encontrado",
    "inst.noScreenshots": "Nenhuma captura encontrada",
    "inst.screenshotHint": "Pressione F2 no jogo para tirar capturas e elas apareceram aqui automaticamente.",
    "inst.screenshots": "capturas",
    "inst.screenshot": "captura",
    "inst.refresh": "Atualizar",
    "inst.openFolder": "Abrir pasta",
    "inst.openInFolder": "Abrir na pasta",
    "inst.copyFilename": "Copiar nome",
    "inst.copyPath": "Copiar caminho completo",
    "inst.rename": "Renomear",
    "inst.move": "Mover",
    "inst.delete": "Excluir",
    "inst.discard": "Descartar",
    "inst.save": "Salvar",
    "inst.emptyFolder": "Pasta vazia",
    "inst.exportTitle": "Exportar modpack",
    "inst.exportName": "Nome do modpack",
    "inst.exportVersion": "Numero da versao",
    "inst.exportDescription": "Descricao",
    "inst.exportDescPlaceholder": "Digite a descricao do modpack...",
    "inst.exportFiles": "Configure quais arquivos sao incluidos nesta exportacao",
    "inst.exportSuccess": "Exportado com sucesso!",
    "inst.exporting": "Exportando...",
    "inst.export": "Exportar",
    "inst.files": "Arquivos",
    "inst.exportMenuItem": "Exportar",
    "inst.exportSaveAs": "Salvar como .mrstack",
    "inst.importedSuccess": "importada com sucesso!",
    "inst.importError": "Erro ao importar",
    "inst.createdSuccess": "criada",
    "inst.deletedToast": "Instancia excluida",
    "inst.savedToast": "Alteracoes salvas",
    "inst.modRemoved": "removido",
    "inst.modUpdated": "atualizado",
    "inst.modInstalled": "instalado com sucesso",
    "inst.errorInstalling": "Erro ao instalar",
    "inst.errorToggling": "Erro ao ativar/desativar mod",
    "inst.errorUpdating": "Erro ao atualizar mod",
    "inst.errorRemoving": "Erro ao remover mod",
    "inst.errorSaving": "Erro ao salvar",
    "inst.errorDeleting": "Erro ao excluir",
    "inst.errorRenaming": "Erro ao renomear",
    "inst.errorOpenFolder": "Nao foi possivel abrir a pasta",
    "inst.screenshotDeleted": "Captura excluida",
    "inst.errorDeletingScreenshot": "Erro ao excluir captura",
    "inst.errorOpeningScreenshot": "Erro ao abrir captura",
    "inst.errorOpeningScreenshotsFolder": "Erro ao abrir a pasta de capturas",
    "inst.fileSaved": "Arquivo salvo",
    "inst.errorSavingFile": "Erro ao salvar",
    "inst.lines": "linhas",
    "inst.featured": "Destaque",
    "inst.latest": "Ultima",
    "inst.by": "por",
    "inst.updatedAgo": "Atualizado",
    "inst.noDescription": "Sem descricao",
    "inst.compatibility": "Compatibilidade",
    "inst.platforms": "Plataformas",
    "inst.tags": "Tags",
    "inst.license": "Licenca",
    "inst.lastUpdated": "Ultima atualizacao",
    "inst.gameVersions": "Versoes do jogo",
    "inst.channels": "Canais",
    "inst.showAllVersions": "Mostrar todas as versoes",
    "inst.openOriginal": "Abrir original",
    "inst.openCurseForge": "CurseForge",
    "inst.noVersionsFound": "Nenhuma versao encontrada",
    "inst.all": "Todos",
    "inst.mods": "Mods",
    "inst.resourcePacks": "Pacotes de recursos",
    "inst.dataPacks": "Pacotes de dados",
    "inst.shaders": "Shaders",
    "inst.version": "Versao",
    "inst.sortBy2": "Ordenar por",
    "inst.view": "Ver",
    "inst.modrinthSource": "Modrinth",
    "inst.curseforgeSource": "CurseForge",
  },
} as const;

export type TranslationKey = keyof typeof dictionaries.en;

export const languageOptions: { value: LauncherLanguage; label: string }[] = [
  { value: "en", label: "English" },
  { value: "es", label: "Español" },
  { value: "pt", label: "Portugues" },
];

function loadLanguage(): LauncherLanguage {
  if (typeof localStorage === "undefined") return "en";
  const stored = localStorage.getItem(STORAGE_KEY);
  return stored === "es" || stored === "pt" || stored === "en" ? stored : "en";
}

interface LanguageState {
  language: LauncherLanguage;
  setLanguage: (language: LauncherLanguage) => void;
  t: (key: TranslationKey) => string;
}

export const useLanguage = create<LanguageState>((set, get) => ({
  language: loadLanguage(),
  setLanguage: (language) => {
    if (typeof localStorage !== "undefined") {
      localStorage.setItem(STORAGE_KEY, language);
    }
    set({ language });
  },
  t: (key) => dictionaries[get().language][key] || dictionaries.en[key],
}));

export function useLauncherTranslation() {
  const language = useLanguage((state) => state.language);
  return (key: TranslationKey) => dictionaries[language][key] || dictionaries.en[key];
}
